services:
  api-1:
    build:
      context: .
      dockerfile: apps/food-delivery/Dockerfile
    container_name: api-1
    ports:
      - "3001:3000"
    env_file:
      - "./apps/food-delivery/.env"
    environment:
      - SERVER_ID=api-1
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: 256M
    mem_reservation: 128M
    networks:
      - food-network

  api-2:
    build:
      context: .
      dockerfile: apps/food-delivery/Dockerfile
    container_name: api-2
    ports:
      - "3002:3000"
    env_file:
      - "./apps/food-delivery/.env"
    environment:
      - SERVER_ID=api-2
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: 256M
    mem_reservation: 128M
    networks:
      - food-network

  api-3:
    build:
      context: .
      dockerfile: apps/food-delivery/Dockerfile
    container_name: api-3
    ports:
      - "3003:3000"
    env_file:
      - "./apps/food-delivery/.env"
    environment:
      - SERVER_ID=api-3
    restart: unless-stopped
    cpus: "0.5"
    mem_limit: 256M
    mem_reservation: 128M
    networks:
      - food-network

  nginx:
    image: nginx:alpine
    container_name: food-delivery-nginx
    env_file:
      - "./apps/food-delivery/.env"
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./apps/food-delivery/nginx/nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./apps/food-delivery/nginx/entrypoint.sh:/etc/nginx/entrypoint.sh:ro
      - ./apps/food-delivery/nginx/logs:/var/log/nginx
    depends_on:
      - api-1
      - api-2
      - api-3
    networks:
      - food-network
    restart: unless-stopped
    command: /etc/nginx/entrypoint.sh
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  # monitoring services
  prometheus:
    image: prom/prometheus:latest
    container_name: food-delivery-prometheus
    volumes:
      - ./apps/food-delivery/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - food-network

  grafana:
    image: grafana/grafana:latest
    container_name: food-delivery-grafana
    ports:
      - "5050:3000"
    volumes:
      - ./apps/food-delivery/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./apps/food-delivery/monitoring/grafana/dashboards:/etc/grafana/dashboards:ro
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - food-network
    depends_on:
      - prometheus

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy noeviction
    ports:
      - "6379:6379"
    networks:
      - food-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-storage:
  redis-data:

networks:
  food-network:
    driver: bridge
